name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/windows.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/windows.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.15.2]
        qt_arch: [clang_64]
    env:
      targetName: KarenMeu
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          modules: qtwebengine
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          
      - run: |
          cd 3rdparty/vtextedit
          git pull
          git submodule init
          git submodule update
          
      - name: build macos
        run: |
          cd 3rdparty/scintilla/qt/ScintillaEdit
          python WidgetGen.py
          cd ../../../..
          cd utils
          make
          cd ..
          cd server
          go build -ldflags="-s -w" -o KarenMeuCloud
          cd ..
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ../${{ env.targetName }}.pro
          make -j 2
          cd ..

      - name: package
        run: |
          cd build
          if [ ! -d client/${{ env.targetName }}.app/Contents/Frameworks ]; then mkdir -p client/${{ env.targetName }}.app/Contents/Frameworks; fi
          if [ ! -d client/${{ env.targetName }}.app/Contents/Frameworks/ScintillaEdit.framework ]; then cp -R 3rdparty/scintilla/bin/ScintillaEdit.framework client/${{ env.targetName }}.app/Contents/Frameworks/; fi
          if [ ! -d client/${{ env.targetName }}.app/Contents/Frameworks/VSyntaxHighlighting.framework ]; then cp -R 3rdparty/vtextedit/src/libs/syntax-highlighting/VSyntaxHighlighting.framework client/${{ env.targetName }}.app/Contents/Frameworks/; fi
          if [ ! -d client/${{ env.targetName }}.app/Contents/Frameworks/VTextEdit.framework ]; then cp -R 3rdparty/vtextedit/src/editor/VTextEdit.framework client/${{ env.targetName }}.app/Contents/Frameworks/; fi
          install_name_tool -change @executable_path/../Frameworks/ScintillaEdit.framework/Versions/4/ScintillaEdit @rpath/ScintillaEdit.framework/Versions/4/ScintillaEdit client/${{ env.targetName }}.app/Contents/MacOS/${{ env.targetName }}
          install_name_tool -change VSyntaxHighlighting.framework/Versions/1/VSyntaxHighlighting @rpath/VSyntaxHighlighting.framework/Versions/1/VSyntaxHighlighting client/${{ env.targetName }}.app/Contents/MacOS/${{ env.targetName }} 
          install_name_tool -change VTextEdit.framework/Versions/1/VTextEdit @rpath/VTextEdit.framework/Versions/1/VTextEdit client/${{ env.targetName }}.app/Contents/MacOS/${{ env.targetName }}
          macdeployqt "client/${{ env.targetName }}.app" -qmldir=. -verbose=1 -dmg
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: "build/client/${{ env.targetName }}.dmg"
          
