name: MacOS
on: 
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/windows.yml'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.github/workflows/windows.yml'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        qt_ver: [5.15.1]
        qt_arch: [clang_64]
    env:
      targetName: KarenMeu
    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_ver }}
          modules: qtwebengine
      
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          submodules: true
          
      - name: build macos
        run: |
          cd 3rdparty/scintilla/qt/ScintillaEdit
          python WidgetGen.py
          cd ../../../..
          cd renderer
          make
          cd ..
          mkdir build
          cd build
          qmake -r CONFIG+=release CONFIG+=qtquickcompiler ../${{ env.targetName }}.pro
          make -j 2
          cd ..
      # tag 打包
      - name: package
        run: |
          cd build
          macdeployqt "client/${{ env.targetName }}.app" -qmldir=. -verbose=1 -dmg
          
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: ${{ env.targetName }}-${{ matrix.qt_arch }}
          path: "build/client/${{ env.targetName }}.dmg"
          